### ISSUE TITLE
Postgres doesn't work

### ISSUE THREAD

**Issue by enticedwanderer** [investbrainapp/investbrain#81]
Laravel and db migrations are not functional with postgres database. It tries for 1 minute to see if the database is available (which it is) but the actual issue is the following:

```bash
root@dockerino:/docker/config/investibrain# dc exec app bash
071f3a4e94b4:/var/app# php artisan migrate --force

   Illuminate\Database\QueryException

  could not find driver (Connection: pgsql, SQL: select exists (select 1 from pg_class c, pg_namespace n where n.nspname = 'public' and c.relname = 'migrations' and c.relkind in ('r', 'p') and n.oid = c.relnamespace))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:825
    821▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    822▕                 );
    823▕             }
    824▕
  ➜ 825▕             throw new QueryException(
    826▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    827▕             );
    828▕         }
    829▕     }

      +39 vendor frames

  40  artisan:13
      Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
```

My docker compose:

```yaml
services:
  app:
    image: investbrainapp/investbrain:latest
    container_name: investbrain-app
    restart: always
    tty: true
    env_file:
      - .env
    volumes:
      - storage:/var/app/storage
    networks:
      - investbrain-network
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.investbrain-https.rule=Host(`investbrain.home.lan`)
      - traefik.http.routers.investbrain-https.entrypoints=web,web-secure
      - traefik.http.routers.investbrain-https.middlewares=secured@file
      - traefik.http.routers.investbrain-https.service=investbrain
      - traefik.http.services.investbrain.loadbalancer.server.port=80
      - wud.watch=true
      - wud.tag.include=^\d+\.\d+\.\d+$$
  investbrain-redis:
    image: redis:alpine
    container_name: investbrain-redis
    restart: always
    command:
      - --loglevel warning
    volumes:
      - investbrain-redis:/data
    networks:
      - investbrain-network
  investbrain-postgres:
    image: postgres:17-alpine
    container_name: investbrain-postgres
    restart: always
    volumes:
      - investbrain-postgres:/var/lib/postgresql/data
    networks:
      - investbrain-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
volumes:
  storage:
  investbrain-redis:
  investbrain-postgres:
networks:
  investbrain-network:
  traefik-network:
    external: true
```

Portion of the `.env` file:

```
...
DB_CONNECTION=pgsql
DB_HOST=investbrain-postgres
DB_PORT=5432
DB_DATABASE=investbrain
DB_USERNAME=investbrain
DB_PASSWORD=<some_secret>

POSTGRES_DB=investbrain
POSTGRES_USER=investbrain
POSTGRES_PASSWORD=<some_secret>
...
```

Should be easy to reproduce.
